# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # secret_key_base: 394d30e1926ec7cd0041dfddcaafac2f574215a67de2352c17be56d452b3ff6943eb9f8518e63a2728960748eaddc895b410d7b77067d9a71753e3e0bdd2b722
  #
  # google_client_id: 79818192381-t6fqtqihvv2i5tl9p77gobc1u93kdff6.apps.googleusercontent.com
  # google_client_secret: 4D6BSN38SpVbG3IQA6hODZ2i

    secret_key_base: ENV["SECRET_KEY_BASE"]

    # google_client_id: ENV["GOOGLE_CLIENT_ID"]
    # google_client_secret: ENV["GOOGLE_CLIENT_SECRET"]

    # google_client_id: ENV["GOOGLE_CLIENT_ID"]
    # google_client_secret: ENV["GOOGLE_CLIENT_SECRET"]

    # google_client_id: 79818192381-t6fqtqihvv2i5tl9p77gobc1u93kdff6.apps.googleusercontent.com
    # google_client_secret: 4D6BSN38SpVbG3IQA6hODZ2i


test:
  secret_key_base: ea52fdb26b8bbf2f3a920760b14e89cd469a0576aecba54f9a4bcd2b3ed23994f9947535120ef2d655580f1a28a5a9afc83284a6561836a252830f9539a94ae6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ENV["SECRET_KEY_BASE"]

  google_client_id: ENV["GOOGLE_CLIENT_ID"]
  google_client_secret: ENV["GOOGLE_CLIENT_SECRET"]
